# Dependabot configuration for automated security updates
# Documentation: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Python dependencies in requirements.txt
  - package-ecosystem: "pip"
    directory: "/airflow"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "security"
      include: "scope"
    reviewers:
      - "euvaldoferreira"
    labels:
      - "security"
      - "dependencies"
    # Ignore patch updates for stable packages
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "security"
      include: "scope"
    reviewers:
      - "euvaldoferreira"
    labels:
      - "security"
      - "docker"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "ci"
      - "github-actions"